-- MySQL Script generated by MySQL Workbench
-- Thu Nov 26 23:53:10 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema apollo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `apollo` ;

-- -----------------------------------------------------
-- Schema apollo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `apollo` DEFAULT CHARACTER SET utf8 ;
USE `apollo` ;

-- -----------------------------------------------------
-- Table `apollo`.`genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apollo`.`genre` ;

CREATE TABLE IF NOT EXISTS `apollo`.`genre` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `row_version` DATETIME(6) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `deleted` BIT(1) NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apollo`.`movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apollo`.`movie` ;

CREATE TABLE IF NOT EXISTS `apollo`.`movie` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `row_version` DATETIME(6) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `genre` BIGINT NOT NULL,
  `duration` BIGINT NOT NULL,
  `image` LONGBLOB NOT NULL,
  `trailer` TEXT NULL,
  `rating` INT NOT NULL DEFAULT 0,
  `deleted` BIT(1) NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`id`),
  INDEX `genre_id_fk_idx` (`genre` ASC) VISIBLE,
  CONSTRAINT `genre_id_fk`
    FOREIGN KEY (`genre`)
    REFERENCES `apollo`.`genre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
KEY_BLOCK_SIZE = 2;


-- -----------------------------------------------------
-- Table `apollo`.`actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apollo`.`actor` ;

CREATE TABLE IF NOT EXISTS `apollo`.`actor` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `row_version` DATETIME(6) NOT NULL,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  `deleted` BIT(1) NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apollo`.`movie_actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apollo`.`movie_actor` ;

CREATE TABLE IF NOT EXISTS `apollo`.`movie_actor` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `movie_id` BIGINT NOT NULL,
  `actor_id` BIGINT NOT NULL,
  `row_version` DATETIME(6) NOT NULL,
  `deleted` BIT(1) NOT NULL DEFAULT FALSE,
  INDEX `actor_id_fk_idx` (`actor_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `movie_id_fk`
    FOREIGN KEY (`movie_id`)
    REFERENCES `apollo`.`movie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `actor_id_fk`
    FOREIGN KEY (`actor_id`)
    REFERENCES `apollo`.`actor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apollo`.`cinema_hall`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apollo`.`cinema_hall` ;

CREATE TABLE IF NOT EXISTS `apollo`.`cinema_hall` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `row_version` DATETIME(6) NOT NULL,
  `label` VARCHAR(255) NOT NULL,
  `size_row` INT NOT NULL,
  `size_column` INT NOT NULL,
  `deleted` BIT(1) NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apollo`.`row_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apollo`.`row_category` ;

CREATE TABLE IF NOT EXISTS `apollo`.`row_category` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `row_version` DATETIME(6) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `price_factor` DOUBLE NOT NULL,
  `deleted` BIT(1) NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apollo`.`row`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apollo`.`row` ;

CREATE TABLE IF NOT EXISTS `apollo`.`row` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `row_version` DATETIME(6) NOT NULL,
  `number` INT NOT NULL,
  `category` BIGINT NOT NULL,
  `cinema_hall` BIGINT NOT NULL,
  `deleted` BIT(1) NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`id`),
  INDEX `cinema_hall_id_fk_idx` (`cinema_hall` ASC) VISIBLE,
  INDEX `category_id_fk_idx` (`category` ASC) VISIBLE,
  CONSTRAINT `category_id_fk`
    FOREIGN KEY (`category`)
    REFERENCES `apollo`.`row_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cinema_hall_id_fk`
    FOREIGN KEY (`cinema_hall`)
    REFERENCES `apollo`.`cinema_hall` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apollo`.`seat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apollo`.`seat` ;

CREATE TABLE IF NOT EXISTS `apollo`.`seat` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `row_version` DATETIME(6) NOT NULL,
  `row_id` BIGINT NOT NULL,
  `number` INT NOT NULL,
  `locked` BIT(1) NOT NULL,
  `layout_column` INT NOT NULL,
  `layout_row` INT NOT NULL,
  `deleted` BIT(1) NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`id`),
  CONSTRAINT `row_id_fk`
    FOREIGN KEY (`row_id`)
    REFERENCES `apollo`.`row` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apollo`.`schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apollo`.`schedule` ;

CREATE TABLE IF NOT EXISTS `apollo`.`schedule` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `row_version` DATETIME(6) NOT NULL,
  `start_time` DATETIME NOT NULL,
  `movie` BIGINT NOT NULL,
  `cinema_hall` BIGINT NOT NULL,
  `price` DECIMAL(15,2) NOT NULL,
  `deleted` BIT(1) NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`id`),
  INDEX `movie_id_fk_idx` (`movie` ASC) VISIBLE,
  INDEX `cinema_hall_id_fk_idx` (`cinema_hall` ASC) VISIBLE,
  CONSTRAINT `movie_schedule_id_fk`
    FOREIGN KEY (`movie`)
    REFERENCES `apollo`.`movie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cinema_hall_schedule_id_fk`
    FOREIGN KEY (`cinema_hall`)
    REFERENCES `apollo`.`cinema_hall` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apollo`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apollo`.`city` ;

CREATE TABLE IF NOT EXISTS `apollo`.`city` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `row_version` DATETIME(6) NOT NULL,
  `postal_code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `deleted` BIT(1) NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apollo`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apollo`.`address` ;

CREATE TABLE IF NOT EXISTS `apollo`.`address` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `row_version` DATETIME(6) NOT NULL,
  `street` VARCHAR(255) NOT NULL,
  `number` INT NOT NULL,
  `city_id` BIGINT NOT NULL,
  `deleted` BIT(1) NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`id`),
  INDEX `city_id_fk_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `city_id_fk`
    FOREIGN KEY (`city_id`)
    REFERENCES `apollo`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apollo`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apollo`.`role` ;

CREATE TABLE IF NOT EXISTS `apollo`.`role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `row_version` DATETIME(6) NOT NULL,
  `label` VARCHAR(255) NOT NULL,
  `max_reservations` INT NOT NULL,
  `deleted` BIT(1) NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apollo`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apollo`.`user` ;

CREATE TABLE IF NOT EXISTS `apollo`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `row_version` DATETIME(6) NOT NULL,
  `uuid` VARCHAR(36) NOT NULL,
  `role` BIGINT NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `address_id` BIGINT NOT NULL,
  `deleted` BIT(1) NOT NULL DEFAULT FALSE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE,
  INDEX `customer_type_fk_idx` (`role` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `address_id_fk_idx` (`address_id` ASC) VISIBLE,
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  CONSTRAINT `address_id_fk`
    FOREIGN KEY (`address_id`)
    REFERENCES `apollo`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `role_id_fk`
    FOREIGN KEY (`role`)
    REFERENCES `apollo`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apollo`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apollo`.`ticket` ;

CREATE TABLE IF NOT EXISTS `apollo`.`ticket` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `row_version` DATETIME(6) NULL,
  `deleted` BIT(1) NULL DEFAULT FALSE,
  `printed` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apollo`.`reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apollo`.`reservation` ;

CREATE TABLE IF NOT EXISTS `apollo`.`reservation` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `row_version` DATETIME(6) NOT NULL,
  `schedule_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `deleted` BIT(1) NOT NULL DEFAULT FALSE,
  `ticket_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `shedule_id_fk_idx` (`schedule_id` ASC) VISIBLE,
  INDEX `user_id_fk_idx` (`user_id` ASC) VISIBLE,
  INDEX `reservation_ticket_id_fk_idx` (`ticket_id` ASC) VISIBLE,
  CONSTRAINT `shedule_id_fk`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `apollo`.`schedule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `apollo`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `reservation_ticket_id_fk`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `apollo`.`ticket` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apollo`.`seat_reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apollo`.`seat_reservation` ;

CREATE TABLE IF NOT EXISTS `apollo`.`seat_reservation` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `reservation_id` BIGINT NOT NULL,
  `seat_id` BIGINT NOT NULL,
  `row_version` DATETIME(6) NOT NULL,
  `deleted` BIT(1) NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`id`),
  INDEX `seat_id_fk_idx` (`seat_id` ASC) VISIBLE,
  CONSTRAINT `reservation_id_fk`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `apollo`.`reservation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `seat_id_fk`
    FOREIGN KEY (`seat_id`)
    REFERENCES `apollo`.`seat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- INDICIES `apollo`
-- -----------------------------------------------------
CREATE INDEX IF NOT EXISTS `idx_schedule_start_time`  ON `apollo`.`schedule` (start_time) COMMENT '' ALGORITHM DEFAULT LOCK DEFAULT;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
