//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apollo.Terminal.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apollo.Terminal.I18N.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card expired.
        /// </summary>
        public static string Card_expired {
            get {
                return ResourceManager.GetString("Card_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card reported as lost.
        /// </summary>
        public static string Card_reported_as_lost {
            get {
                return ResourceManager.GetString("Card_reported_as_lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card validation failed.
        /// </summary>
        public static string Card_validation_failed {
            get {
                return ResourceManager.GetString("Card_validation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast.
        /// </summary>
        public static string Cast {
            get {
                return ResourceManager.GetString("Cast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection lost.
        /// </summary>
        public static string Connection_lost {
            get {
                return ResourceManager.GetString("Connection_lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVC.
        /// </summary>
        public static string CreditCardCvc {
            get {
                return ResourceManager.GetString("CreditCardCvc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CreditCardName {
            get {
                return ResourceManager.GetString("CreditCardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card number.
        /// </summary>
        public static string CreditCardNumber {
            get {
                return ResourceManager.GetString("CreditCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid until.
        /// </summary>
        public static string CreditCardValidUntil {
            get {
                return ResourceManager.GetString("CreditCardValidUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo.
        /// </summary>
        public static string General_ProductName {
            get {
                return ResourceManager.GetString("General_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Genre_Action {
            get {
                return ResourceManager.GetString("Genre_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventure.
        /// </summary>
        public static string Genre_Adventure {
            get {
                return ResourceManager.GetString("Genre_Adventure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Genres.
        /// </summary>
        public static string Genre_All {
            get {
                return ResourceManager.GetString("Genre_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation.
        /// </summary>
        public static string Genre_Animation {
            get {
                return ResourceManager.GetString("Genre_Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biography.
        /// </summary>
        public static string Genre_Biography {
            get {
                return ResourceManager.GetString("Genre_Biography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comedy.
        /// </summary>
        public static string Genre_Comedy {
            get {
                return ResourceManager.GetString("Genre_Comedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crime.
        /// </summary>
        public static string Genre_Crime {
            get {
                return ResourceManager.GetString("Genre_Crime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drama.
        /// </summary>
        public static string Genre_Drama {
            get {
                return ResourceManager.GetString("Genre_Drama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string Genre_Family {
            get {
                return ResourceManager.GetString("Genre_Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fantasy.
        /// </summary>
        public static string Genre_Fantasy {
            get {
                return ResourceManager.GetString("Genre_Fantasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film-Noir.
        /// </summary>
        public static string Genre_Film_Noir {
            get {
                return ResourceManager.GetString("Genre_Film-Noir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string Genre_History {
            get {
                return ResourceManager.GetString("Genre_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horror.
        /// </summary>
        public static string Genre_Horror {
            get {
                return ResourceManager.GetString("Genre_Horror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string Genre_Music {
            get {
                return ResourceManager.GetString("Genre_Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musical.
        /// </summary>
        public static string Genre_Musical {
            get {
                return ResourceManager.GetString("Genre_Musical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mystery.
        /// </summary>
        public static string Genre_Mystery {
            get {
                return ResourceManager.GetString("Genre_Mystery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romance.
        /// </summary>
        public static string Genre_Romance {
            get {
                return ResourceManager.GetString("Genre_Romance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sci-Fi.
        /// </summary>
        public static string Genre_Sci_Fi {
            get {
                return ResourceManager.GetString("Genre_Sci-Fi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport.
        /// </summary>
        public static string Genre_Sport {
            get {
                return ResourceManager.GetString("Genre_Sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thriller.
        /// </summary>
        public static string Genre_Thriller {
            get {
                return ResourceManager.GetString("Genre_Thriller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to War.
        /// </summary>
        public static string Genre_War {
            get {
                return ResourceManager.GetString("Genre_War", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western.
        /// </summary>
        public static string Genre_Western {
            get {
                return ResourceManager.GetString("Genre_Western", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo.
        /// </summary>
        public static string Heading_Title {
            get {
                return ResourceManager.GetString("Heading_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient funds.
        /// </summary>
        public static string Insufficient_funds {
            get {
                return ResourceManager.GetString("Insufficient_funds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credit card number.
        /// </summary>
        public static string Invalid_card {
            get {
                return ResourceManager.GetString("Invalid_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CVC.
        /// </summary>
        public static string Invalid_CreditCardCvc {
            get {
                return ResourceManager.GetString("Invalid_CreditCardCvc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid expiration date.
        /// </summary>
        public static string Invalid_CreditCardDate {
            get {
                return ResourceManager.GetString("Invalid_CreditCardDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name.
        /// </summary>
        public static string Invalid_CreditCardName {
            get {
                return ResourceManager.GetString("Invalid_CreditCardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name.
        /// </summary>
        public static string Invalid_name {
            get {
                return ResourceManager.GetString("Invalid_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while fetching movies.
        /// </summary>
        public static string Movies_Failed_Loading {
            get {
                return ResourceManager.GetString("Movies_Failed_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No movie(s) found!.
        /// </summary>
        public static string No_Movie {
            get {
                return ResourceManager.GetString("No_Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APOLLO.
        /// </summary>
        public static string Overlay_Title {
            get {
                return ResourceManager.GetString("Overlay_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a error during printing process.
        /// </summary>
        public static string Print_Error {
            get {
                return ResourceManager.GetString("Print_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservations.
        /// </summary>
        public static string Reservations {
            get {
                return ResourceManager.GetString("Reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules.
        /// </summary>
        public static string Schedules {
            get {
                return ResourceManager.GetString("Schedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum amount of seat reservations reached.
        /// </summary>
        public static string Seat_Max_Reservations {
            get {
                return ResourceManager.GetString("Seat_Max_Reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat is occupied or locked.
        /// </summary>
        public static string Seat_Occupied {
            get {
                return ResourceManager.GetString("Seat_Occupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule has already begun.
        /// </summary>
        public static string Seat_Schedule_Begun {
            get {
                return ResourceManager.GetString("Seat_Schedule_Begun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No schedule found for reservation.
        /// </summary>
        public static string Seat_Schedule_Null {
            get {
                return ResourceManager.GetString("Seat_Schedule_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred during the reservation process.
        /// </summary>
        public static string Seat_Unexpected {
            get {
                return ResourceManager.GetString("Seat_Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choosen seats must be either a block of seats or be Covid-19 conform.
        /// </summary>
        public static string Seat_Validation {
            get {
                return ResourceManager.GetString("Seat_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string Step_Checkout {
            get {
                return ResourceManager.GetString("Step_Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Step_Payment {
            get {
                return ResourceManager.GetString("Step_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select seat.
        /// </summary>
        public static string Step_SelectSeat {
            get {
                return ResourceManager.GetString("Step_SelectSeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Stepper_Back {
            get {
                return ResourceManager.GetString("Stepper_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Stepper_Cancel {
            get {
                return ResourceManager.GetString("Stepper_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Stepper_Next {
            get {
                return ResourceManager.GetString("Stepper_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select seat.
        /// </summary>
        public static string StepSelectSeat {
            get {
                return ResourceManager.GetString("StepSelectSeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Ticket.
        /// </summary>
        public static string Ticket_Print {
            get {
                return ResourceManager.GetString("Ticket_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string Ticket_Row {
            get {
                return ResourceManager.GetString("Ticket_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat(s).
        /// </summary>
        public static string Ticket_Seat {
            get {
                return ResourceManager.GetString("Ticket_Seat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
    }
}
